version: 2
jobs:
  build:
    machine: true
    
    working_directory: ~/repo

    branches:
      only:
        - master
    
    dependencies:
      override:
        - pip install -r requirements.txt

    steps:
      - checkout
      - run: |
        docker run -d -e POSTGRES_USER=odoo -e POSTGRES_PASSWORD=odoo --name db postgres:9.4
      - run: |
        docker run -p 8069:8069 --name odoo --link db:db -t odoo
      - run: |
        docker workstart -a odoo

    test:
      - lettuce tests/


      #build
      #- run: if [ "${CIRCLE_BRANCH}" == "master" ]; then bash ./scripts_circle/build_master.sh; fi



      #deploy
      #- run: if [ "${CIRCLE_BRANCH}" == "master" ]; then bash ./bin_deploy/scripts_circle/deploy_master.sh; fi #&& bash ./bin_deploy/scripts_circle/deploy_test_workers.sh; fi