version: 2
jobs:
  build:
    working_directory: ~/repo
    branches:
      only:
        - master
    docker:
      - image: ubuntu:16.04
      - image: circleci/postgres:9.5
        environment:
          POSTGRES_USER: odoo
          POSTGRES_DB: db
          POSTGRES_PASSWORD: odoo
    
    
    dependencies:
      pre:
        - sudo apt-get update; sudo apt-get install gnu-smalltalk wget
      override:
        - pip install -r requirements.txt
    
    steps:
      - checkout
      - run:
          name: install dockerize
          environment:
            DOCKERIZE_VERSION: v0.3.0          
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

      
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      #- run: docker -p 8069:8069 --name odoo --link db:db -t odoo
      #- run: docker workstart -a odoo

    #test:
    #  - lettuce tests/
    #   - coverage run --omit='*lettuce*,*fuzzywuzzy*' tests/features/steps.py 
    # - coverage report -m
    # - nosetests --with-doctest --with-coverage -s app


      #build
      #- run: if [ "${CIRCLE_BRANCH}" == "master" ]; then bash ./scripts_circle/build_master.sh; fi



      #deploy
      #- run: if [ "${CIRCLE_BRANCH}" == "master" ]; then bash ./bin_deploy/scripts_circle/deploy_master.sh; fi #&& bash ./bin_deploy/scripts_circle/deploy_test_workers.sh; fi