version: 2
jobs:
  build:
    working_directory: ~/repo
    branches:
      only:
        - master
    docker:
      - image: circleci/python:3.6.1
     
    
    dependencies:
      override:
        - apt install -y git build-essential libssl-dev curl apt-transport-https ca-certificates software-properties-common libsasl2-dev python-dev libldap2-dev python3-dev libpng-dev zlib1g-dev libjpeg-dev python3-pip        
        - pip install -r requirements.txt
    
    steps:
      - checkout
      - run:
          command: |
            python3 --version

      - run:
          command: |
            v=$(python3 --version 2>& 1); if [ "$v" == "Python 3.6.1" ]; then echo "$v OK"; else ! echo "$v ERR"; fi
      - run:
          command: |
            python3 -c 'print("OK")'

      - run:
          command: |
            pip3 install --upgrade pip
            
      - run:
          command: |
            pip install -r requirements.txt

      - run:
          ./src_code/odoo-11.0/odoo-bin --addons-path=addons --db-filter=bca_prueba_00 --db_port=5432 --db_host=bcadbdev.chociozqc8if.us-east-1.rds.amazonaws.com --db_password=odoo --db_user=odoo


      #- run: docker -p 8069:8069 --name odoo --link db:db -t odoo
      #- run: docker workstart -a odoo

    #test:
    #  - lettuce tests/
    #   - coverage run --omit='*lettuce*,*fuzzywuzzy*' tests/features/steps.py 
    # - coverage report -m
    # - nosetests --with-doctest --with-coverage -s app


      #build
      #- run: if [ "${CIRCLE_BRANCH}" == "master" ]; then bash ./scripts_circle/build_master.sh; fi



      #deploy
      #- run: if [ "${CIRCLE_BRANCH}" == "master" ]; then bash ./bin_deploy/scripts_circle/deploy_master.sh; fi #&& bash ./bin_deploy/scripts_circle/deploy_test_workers.sh; fi