version: 2
jobs:
  build:
    working_directory: ~/repo
    branches:
      only:
        - master
    docker:
      - image: circleci/postgres:9.5
        environment:
          POSTGRES_USER: odoo
          POSTGRES_DB: db
          POSTGRES_PASSWORD: odoo
    
    
    dependencies:
      override:
        - pip install -r requirements.txt
    steps:
      - checkout
      - run:
        name: Wait for DB
        command: dockerize -wait tcp://localhost:5432 -timeout 1m

      #- run: docker -p 8069:8069 --name odoo --link db:db -t odoo
      #- run: docker workstart -a odoo

    #test:
    #  - lettuce tests/


      #build
      #- run: if [ "${CIRCLE_BRANCH}" == "master" ]; then bash ./scripts_circle/build_master.sh; fi



      #deploy
      #- run: if [ "${CIRCLE_BRANCH}" == "master" ]; then bash ./bin_deploy/scripts_circle/deploy_master.sh; fi #&& bash ./bin_deploy/scripts_circle/deploy_test_workers.sh; fi